version: '2'
services:
  wordpress:
    build: .
    volumes:
      - ~/Documents/Docker/FiKickDev/wp-content:/var/www/wp-content
      - ~/Documents/Docker/FiKickDev/wordpress:/usr/src/wordpress
    env_file: .env
    expose:
      - "9000"
    ports:
      - "80:80"
    links:
      - mysql
  mysql:
    image: mariadb:5.5
    ports:
      - "3306:3306"
    volumes:
      - ~/Documents/Docker/FiKickDev/mysql:/var/lib/mysql
    env_file: .env
  ngrok:
    image: wernight/ngrok
    links:
      - wordpress:http
    env_file: .env
    ports:
      - "4040:4040"
